import type { LucideIcon } from 'lucide-react'
import {
  AppWindow,
  Binoculars,
  BookOpen,
  Brain,
  Briefcase,
  Bug,
  Building2,
  CalendarDays,
  CalendarRange,
  ClipboardList,
  Clock,
  Code,
  Database,
  FileCheck,
  FileSpreadsheet,
  FileText,
  Filter,
  FolderOpen,
  GitBranch,
  Github,
  Globe,
  Hash,
  History,
  Languages,
  LayoutTemplate,
  ListChecks,
  ListTodo,
  ListTree,
  Mail,
  MessageSquare,
  NotebookPen,
  Plane,
  Presentation,
  Send,
  Share2,
  ShieldAlert,
  Table2,
  Tag,
  Target,
  Ticket,
} from 'lucide-react'

export const SKILL_ICONS: Record<string, LucideIcon> = {
  'weekly-report': FileText,
  'excel-merge': Table2,
  'ppt-outline': Presentation,
  'file-organize': FolderOpen,
  'meeting-notes': NotebookPen,
  'daily-standup': CalendarDays,
  'email-reply': Mail,
  'research-digest': BookOpen,
  'meeting-agenda': CalendarDays,
  'sop-write': ClipboardList,
  'competitor-brief': Binoculars,
  'job-jd': Briefcase,
  'interview-notes': MessageSquare,
  'contract-checklist': FileCheck,
  'customer-reply': MessageSquare,
  'translate-zh': Languages,
  'social-post': Share2,
  'mindmap-md': ListTree,
  changelog: History,
  'release-notes': Tag,
  'user-story': ListChecks,
  'bug-repro': Bug,
  'code-review-notes': Code,
  'data-clean': Filter,
  'sql-explain': Database,
  'risk-register': ShieldAlert,
  'travel-itinerary': Plane,
  'personal-plan': CalendarRange,
  'proposal-onepager': LayoutTemplate,
  'minutes-todo': ListChecks,
  'expense-table': Table2,
  'weekly-plan': CalendarRange,
  'okrs-draft': Target,
  'notice-write': FileText,
  'mail-followup': Mail,
  'leave-request': CalendarDays,
  'ppt-speaker-notes': Presentation,
  'checklist-qa': ClipboardList,
  'exec-brief': Briefcase,
  'calendar-block': Clock,
  'handover-note': NotebookPen,
  'invoice-check': FileSpreadsheet,
  'policy-digest': BookOpen,
}

export const MCP_ICONS: Record<string, LucideIcon> = {
  filesystem: FolderOpen,
  memory: Brain,
  'sequential-thinking': ListTree,
  fetch: Globe,
  git: GitBranch,
  sqlite: Database,
  puppeteer: AppWindow,
  playwright: AppWindow,
  time: Clock,
  github: Github,
  feishu: Send,
  dingtalk: MessageSquare,
  wecom: Building2,
  notion: BookOpen,
  slack: Hash,
  linear: ListTodo,
  jira: Ticket,
  'google-calendar': CalendarDays,
  mail: Mail,
}

export function firstGlyph(label: string): string {
  const ch = Array.from(label.trim())[0]
  if (!ch) return '?'
  return /[a-z]/.test(ch) ? ch.toUpperCase() : ch
}

const TONES = [
  'bg-primary/10 text-primary',
  'bg-sky-100 text-sky-800',
  'bg-teal-100 text-teal-800',
  'bg-indigo-100 text-indigo-800',
  'bg-cyan-100 text-cyan-800',
] as const

export function toneFor(key: string): string {
  let hash = 0
  for (const ch of key) hash = (hash * 31 + ch.charCodeAt(0)) >>> 0
  return TONES[hash % TONES.length]
}
