import type { McpInfo } from './protocol'

export type ConnectorAuth = 'local' | 'oauth' | 'token'
export type ConnectorCategory = 'local' | 'code' | 'office' | 'chat' | 'docs'

export interface ConnectorTemplate {
  id: string
  name: string
  description: string
  category: ConnectorCategory
  auth: ConnectorAuth
  command: string
  args: string[]
  hint: string
  spawn?: boolean
  tokenEnv?: string
  tokenLabel?: string
  tokenUrl?: string
}

export const CONNECTOR_MARKET: ConnectorTemplate[] = [
  {
    id: 'github',
    name: 'GitHub',
    description: '授权后查询仓库、Issue、PR 与代码变更，适合研发协作。',
    category: 'code',
    auth: 'oauth',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    hint: '优先走浏览器 OAuth。未配置应用时，可粘贴 Personal Access Token。',
    tokenEnv: 'GITHUB_PERSONAL_ACCESS_TOKEN',
    tokenLabel: 'GitHub Personal Access Token',
    tokenUrl: 'https://github.com/settings/tokens',
  },
  {
    id: 'feishu',
    name: '飞书',
    description: '连接飞书文档、知识库与消息，用自然语言查找和整理协作内容。',
    category: 'office',
    auth: 'oauth',
    command: 'npx',
    args: ['-y', '@larksuiteoapi/lark-mcp'],
    hint: '配置飞书开放平台应用后可一键授权，也可粘贴用户访问令牌。',
    tokenEnv: 'USER_ACCESS_TOKEN',
    tokenLabel: '飞书用户访问令牌',
    tokenUrl: 'https://open.feishu.cn/app',
  },
  {
    id: 'dingtalk',
    name: '钉钉',
    description: '登录你自己企业的钉钉账号，可在对话里提交日志。不需要创建应用或填写密钥。',
    category: 'office',
    auth: 'oauth',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    spawn: false,
    hint: '点 + 后在浏览器登录你自己的钉钉。若企业还没开通，按页面提示向管理员申请「CLI 访问管理」。',
  },
  {
    id: 'wecom',
    name: '企业微信',
    description: '绑定企业微信通讯录与日程，协助整理会议、通知和客户跟进。',
    category: 'office',
    auth: 'token',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    spawn: false,
    hint: '在企业微信管理后台创建应用后，粘贴 Secret / Token。',
    tokenEnv: 'WECOM_SECRET',
    tokenLabel: '企业微信应用 Secret',
    tokenUrl: 'https://work.weixin.qq.com',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: '搜索、读取和整理 Notion 页面，把知识库变成对话可用的资料。',
    category: 'docs',
    auth: 'token',
    command: 'npx',
    args: ['-y', '@notionhq/notion-mcp-server'],
    hint: '在 Notion 集成页创建 Internal Integration，粘贴 Token。',
    tokenEnv: 'NOTION_TOKEN',
    tokenLabel: 'Notion Integration Token',
    tokenUrl: 'https://www.notion.so/my-integrations',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: '读取频道摘要与消息线索，协助整理讨论结论。',
    category: 'chat',
    auth: 'token',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-slack'],
    hint: '创建 Slack 应用后粘贴 Bot Token（xoxb-）。',
    tokenEnv: 'SLACK_BOT_TOKEN',
    tokenLabel: 'Slack Bot Token',
    tokenUrl: 'https://api.slack.com/apps',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: '查询与整理 Linear 任务、迭代和缺陷，适合产研周报。',
    category: 'code',
    auth: 'token',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    spawn: false,
    hint: '在 Linear 设置里创建 Personal API Key 后粘贴。',
    tokenEnv: 'LINEAR_API_KEY',
    tokenLabel: 'Linear API Key',
    tokenUrl: 'https://linear.app/settings/api',
  },
  {
    id: 'jira',
    name: 'Jira',
    description: '查询 Jira 工单与迭代，协助写进展和风险说明。',
    category: 'code',
    auth: 'token',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    spawn: false,
    hint: '使用 Atlassian API Token，在账号安全页创建。',
    tokenEnv: 'JIRA_API_TOKEN',
    tokenLabel: 'Jira API Token',
    tokenUrl: 'https://id.atlassian.com/manage-profile/security/api-tokens',
  },
  {
    id: 'google-calendar',
    name: 'Google 日历',
    description: '授权后查看日程，协助安排会议、写纪要和周计划。',
    category: 'office',
    auth: 'oauth',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    spawn: false,
    hint: '配置 Google Cloud OAuth 后可浏览器授权；否则粘贴访问令牌。',
    tokenEnv: 'GOOGLE_ACCESS_TOKEN',
    tokenLabel: 'Google 访问令牌',
    tokenUrl: 'https://console.cloud.google.com/apis/credentials',
  },
  {
    id: 'mail',
    name: '工作邮箱',
    description: '绑定邮箱访问令牌，协助起草回复、整理未读和跟进线程。',
    category: 'office',
    auth: 'token',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    spawn: false,
    hint: '使用邮箱服务商提供的应用专用密码或 OAuth 令牌。',
    tokenEnv: 'MAIL_ACCESS_TOKEN',
    tokenLabel: '邮箱访问令牌 / 应用密码',
    tokenUrl: 'https://mail.google.com',
  },
  {
    id: 'filesystem',
    name: '本地文件系统',
    description: '让 Agent 通过 MCP 访问指定目录（默认用户公共目录，可再改路径）。',
    category: 'local',
    auth: 'local',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', 'C:/Users/Public'],
    hint: '适合需要跨工作空间读公共文件夹时启用。',
  },
  {
    id: 'memory',
    name: '长期记忆',
    description: '跨任务记住偏好和项目事实，存在本机 MCP memory 里。',
    category: 'local',
    auth: 'local',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    hint: '首次启用会下载 npm 包，需能访问 npm 源。',
  },
  {
    id: 'sequential-thinking',
    name: '逐步思考',
    description: '给复杂拆解提供思维链工具，减少一步到位的胡编。',
    category: 'local',
    auth: 'local',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    hint: '适合调研、方案和排错。',
  },
  {
    id: 'fetch',
    name: '网页抓取',
    description: '按 URL 拉取页面正文，补充内置 WebFetch。',
    category: 'local',
    auth: 'local',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-fetch'],
    hint: '若包名安装失败，可在下方自定义 command。',
  },
  {
    id: 'git',
    name: 'Git 仓库',
    description: '在指定仓库里看日志、diff 和状态。',
    category: 'code',
    auth: 'local',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-git', '--repository', 'C:/Users/Public'],
    hint: '启用后把路径改成你的仓库根目录。',
  },
  {
    id: 'sqlite',
    name: 'SQLite 查询',
    description: '只读查询本地 .db，适合对账和抽数。',
    category: 'local',
    auth: 'local',
    command: 'npx',
    args: ['-y', 'mcp-sqlite', 'C:/Users/Public/data.db'],
    hint: '把最后一个参数换成真实 db 路径。',
  },
  {
    id: 'playwright',
    name: '浏览器自动化',
    description: '用 Playwright 打开页面、截图或抽取结构（官方推荐，替代已停更的 Puppeteer MCP）。',
    category: 'local',
    auth: 'local',
    command: 'npx',
    args: ['-y', '@playwright/mcp@latest'],
    hint: '首次启用可能下载浏览器内核，体积较大。',
  },
  {
    id: 'time',
    name: '时区与时间',
    description: '当前时间和时区换算，避免模型胡编日期。',
    category: 'local',
    auth: 'local',
    command: 'npx',
    args: ['-y', 'time-mcp'],
    hint: '轻量工具，适合日程和纪要。',
  },
]

/** 兼容旧引用：本地 MCP 模板 */
export const MCP_MARKET = CONNECTOR_MARKET

export function templateToMcp(item: ConnectorTemplate, env?: Record<string, string>): McpInfo {
  return {
    id: item.id,
    command: item.command,
    args: item.args,
    env,
    scope: 'user',
    approved: true,
    disabled: item.spawn === false,
  }
}
